language: node_js
node_js:
- stable
script:
- gulp test
deploy:
  provider: s3
  bucket: aws-website-joshuatoth-5qrbk
  acl: public_read
  skip_cleanup: true
  local_dir: build
  on:
    branch: master
    tags: true
  secret_access_key:
    secure: cyX/vJ5+7izdmpnQsOybRmvd19atOLgue5cDPqtrvrAMo+lSD016ui5IPbtR1ua7v0NupRhuzfPlO9vIqni7bQDFcsUxLM4pcpcsWFm6LYJ5enwAYulF2OS8lkQ5GZTydqTbCOWi/NclBLohHZpPsVA/ZH9aFOOLimhLIaj+RuAiZ22e649bB0r/cWhlb982hOZWCYyVCVPElX28uk+DHUy34YbAjyHHSliLKgkB14jdE147jb7jToNwXYS3p/hvi2waUmWgoSHSscxqrBCqIkDDM+gOhBrlqk0+F597qkmDW2pelIr24b2ZWR4kATiopxbikqqdyN0bsu6iXqOFhjeoE+SZxnpfWAaKdvZOuqfWNPyy0uUY/61Ya8sNlWuFm0+EY9I0YSk9n0FLTsTa3YALxXpbAok220QuzqeIZDFVoNE9/BeS4AEhBwJSX43WXRJnt0i0Nx57mWbfaqUpZBVRwj6zEMOlsKjP2i4Tsumdz5hzZLHZbwq88G7KVVWq+x/ZjUVAXBacl7fRUxxMGXQ77pCOp5PpyvecO0D+h7IzgeuWdm9JlJf5Ol0Iq46JNXvw7yXXhrVMXR/FViJ0lWSEEyu7GP/2xajOGMVxJPMeGwpP978Hb69Xk6TpDj66o37LeYHLBVFRdAJqf6RQhPZUxif7SHiCZ6vRRLOhwSI=
  access_key_id:
    secure: wOYN5irOEykgpFOUE2jqxOUNWl6gloBlBtdOkvMbtv+LapxgSa6J/I8NNEAdlXJCO54hRxUiuoN0Un8PVrHOt+B/2F3+HcTlaYQ3iGMvim52401QC7JWrcCWh/CGlkL5mSMTkzt1GgpgdaIr2AnpLQuHtTZfLqOwbCeIFgW2NLzADsl7zHOWd7F0mmbPzAtZomzhJQJnxLQ7yVtgzos+RGy9QGxzieGCLk77u5+JITU40P01c+9tDyVMdEajYRNzcBermC8wje3HmAFbNltIQgUAZvLDWTviHz8zTFlqGoU8ogZTAM6vKNRLMOVBWv1udK1GwKHjLQcAXkzd3Ig38AiUWFiWO5kTHuf8b32KiiVN5jRN3+1TpU1pUOfQAKYAxDWAOByoSTTOLE7R28OLeVcaCGBhO8woMbq+GNmxqX5q/E2LTwHToOYN0eyyar01MZoNKtJKuKG+r6xq0bbJ+9R/u4uitGotclkqxC9R9P+s/W6Kp1dx+yegVOYdhD/N/VPyXUpbnxOENxD2Q8Q3BMPcXqqZ0NTHdZXh0JdkW6WPaXvEFAdPSQuz+sRdiY0jvYwVvahPvlMfukVkDgb/GGMnraHqP/GtU8zhBnZ1fc355CHj/nDxXnQ4UIOVhmBbD6KCD9CwKby8rWaPUu0JmzKJWjUxgxKGvpIBTmfXg+w=
